"""Export the detector and scaffold artifacts the release promises, with cards that match.

`artifacts/cards/` carried a dataset card and a scaffold model card while `artifacts/models/`
was empty. The release text promises "model cards for every artifact"; there were two cards and
zero artifacts. An evaluator who follows the reproduction instructions finds nothing to load.

What ships, and why each one:

  detector_<dataset>_seed<k>.json   the XGBoost detector every headline number is computed
                                    against. Saved in XGBoost's own JSON format, so it loads
                                    without pickle and without this package.
  scaffold_<dataset>_seed<k>.json   the A3 scaffolded model. Reproducing the scaffolding attack
                                    needs the poisoned artifact, not a description of it, and
                                    withholding it would make that result unfalsifiable.
  manifest.json                     per artifact: dataset, seed, split protocol, feature order,
                                    class mapping, training rows, held-out accuracy, and the
                                    sha256 of the file.

Feature order is recorded because a saved model is useless without it: the columns a caller
passes must be the columns it was fitted on, and the loader's constant-column drop makes that
order dataset- and version-dependent rather than obvious.

Model weights are gitignored deliberately -- they are derived from corpora under academic-use
terms and are regenerable from this script. The manifest and the cards are tracked, so a reader
can see exactly what would be produced and check it against what they get.

  python scripts/export_model_artifacts.py
  python scripts/export_model_artifacts.py --datasets fiveg_nidd --seeds 0

Regenerated by `make cards`.
"""
from __future__ import annotations

import argparse
import hashlib
import json
import logging
from pathlib import Path

import numpy as np

from avert.benchmark.scaffold import make_scaffolded_detector
from avert.config import load_config
from avert.data.datasets import load_dataset
from avert.data.grouping import grouped_split
from avert.detectors.real import XGBoostDetector

REPO = Path(__file__).resolve().parents[1]
OUT = REPO / "artifacts" / "models"
DATASETS = ["fiveg_nidd", "ciciot2023", "ciciomt2024"]
log = logging.getLogger("model_artifacts")


def sha256(p: Path) -> str:
    h = hashlib.sha256()
    with open(p, "rb") as fh:
        for chunk in iter(lambda: fh.read(1 << 20), b""):
            h.update(chunk)
    return h.hexdigest()


def export(dataset: str, seeds: list[int], n_train: int) -> list[dict]:
    data = load_dataset(dataset, load_config(f"datasets/{dataset}"))
    X, y = data.X, data.y
    entries = []

    for seed in seeds:
        rng = np.random.default_rng(seed)
        split = grouped_split(data.grouping, seed=seed)
        tr = (np.sort(rng.choice(split.train, n_train, replace=False))
              if len(split.train) > n_train else split.train)
        te = split.test

        det = XGBoostDetector(n_estimators=150).fit(X[tr], y[tr])
        acc = float((det.predict(X[te]) == y[te]).mean())

        path = OUT / f"detector_{dataset}_seed{seed}.json"
        path.parent.mkdir(parents=True, exist_ok=True)
        det.booster.save_model(str(path))

        common = {
            "dataset": dataset, "seed": seed,
            "split_protocol": data.grouping.kind,
            "split_is_session_aware": bool(data.grouping.usable),
            "n_train_rows": int(len(tr)), "n_test_rows": int(len(te)),
            "feature_order": list(data.feature_names),
            "class_order": [str(c) for c in (data.label_names or [])],
        }
        entries.append({**common, "artifact": path.name, "kind": "detector",
                        "held_out_accuracy": round(acc, 4), "sha256": sha256(path)})

        # The A3 scaffold. Reproducing that attack needs the poisoned artifact itself, and the
        # poisoned part is the SURROGATE -- `ScaffoldedDetector.booster` deliberately returns the
        # real model, because an exact attributor reads through the wrapper untouched, which is
        # the whole finding. Saving `.booster` would therefore have shipped the clean model under
        # the scaffold's name. Export the surrogate, and record the routing parameters that make
        # the wrapper reconstructable.
        scaffold, _real = make_scaffolded_detector(X[tr], y[tr], n_corrupt=12, seed=seed)
        spath = OUT / f"scaffold_surrogate_{dataset}_seed{seed}.json"
        scaffold.surrogate.booster.save_model(str(spath))
        entries.append({**common, "artifact": spath.name, "kind": "scaffold_a3_surrogate",
                        "note": "The surrogate a Slack-style scaffold routes off-manifold probes "
                                "to, trained with the real model's 12 most important features "
                                "permuted. Rebuild the wrapper as ScaffoldedDetector(real, "
                                "surrogate, OODDetector(contamination=0.3, seed=seed)). An exact "
                                "attributor reads the real model and is NOT fooled -- that is "
                                "architectural, not an empirical finding.",
                        "scaffold_params": {"n_corrupt": 12, "contamination": 0.3, "seed": seed},
                        "sha256": sha256(spath)})
        log.info("%s seed %d: detector held-out accuracy %.4f (%s split), scaffold exported",
                 dataset, seed, acc, data.grouping.kind)
    return entries


def main() -> int:
    ap = argparse.ArgumentParser()
    ap.add_argument("--datasets", nargs="+", default=DATASETS)
    ap.add_argument("--seeds", nargs="+", type=int, default=[0])
    ap.add_argument("--n-train", type=int, default=60_000)
    a = ap.parse_args()
    logging.basicConfig(level=logging.INFO, format="%(message)s")

    entries = []
    for ds in a.datasets:
        entries += export(ds, a.seeds, a.n_train)

    manifest = OUT / "manifest.json"
    manifest.write_text(json.dumps(
        {"generated_by": "scripts/export_model_artifacts.py",
         "note": "Weights are gitignored (derived from academic-use corpora) and regenerable "
                 "from this script; this manifest is tracked so the contents are checkable.",
         "artifacts": entries}, indent=1))
    log.info("exported %d artifacts to %s", len(entries), OUT)
    log.info("manifest: %s", manifest)
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
