"""Export the detector and scaffold artifacts the release promises, with cards that match.

`artifacts/cards/` carried a dataset card and a scaffold model card while `artifacts/models/`
was empty. The release text promises "model cards for every artifact"; there were two cards and
zero artifacts. An evaluator who follows the reproduction instructions finds nothing to load.

What ships, and why each one:

  detector_<dataset>_seed<k>.json   the XGBoost detector every headline number is computed
                                    against. Saved in XGBoost's own JSON format, so it loads
                                    without pickle and without this package.
  scaffold_real_<dataset>_seed<k>.json       the real model the A3 wrapper routes to,
  scaffold_surrogate_<dataset>_seed<k>.json  the surrogate it diverts probes to, and
  scaffold_ood_<dataset>_seed<k>.joblib      the isolation forest that does the routing.
                                    Reproducing the scaffolding attack needs the poisoned
                                    artifact, not a description of it, and withholding it
                                    would make that result unfalsifiable.
  manifest.json                     per artifact: dataset, seed, split protocol, feature order,
                                    class mapping, training rows, held-out accuracy, and the
                                    sha256 of the file.

The detector depends on the dataset and the seed and on nothing else -- a cell's three target
classes share one bit-identical fit, because `_prepare` draws the training rows from the seed
before the target is consulted. So the 45 cells of the matrix are covered by 15 detectors, not
45 files, and the manifest says which cells each one serves. The scaffold's `real` component is
refitted from the same rows and is therefore the same model again; it is exported anyway, with
its sha256 beside the detector's, so a reader can check that rather than take it on trust.

The isolation forest is the one artifact that cannot be JSON: it is a scikit-learn estimator and
travels through joblib, so it needs the same scikit-learn to load. The manifest records that
version and the three parameters that rebuild it from the training rows, which is the route that
does not depend on a pickle.

Feature order is recorded because a saved model is useless without it: the columns a caller
passes must be the columns it was fitted on, and the loader's constant-column drop makes that
order dataset- and version-dependent rather than obvious.

The manifest is tracked wherever the weights are, so a reader can check what they got against
what this script produced: every entry carries the file's sha256, the feature order it was fitted
on, the class mapping, the training-row count and the held-out accuracy. Whether the weight files
themselves are committed is a property of the tree, not of this script -- they are gitignored in
the development tree, where they are regenerable from here and from the corpora, and the public
release decides separately. Do not restate a gitignore policy in the manifest: the same file is
written into both trees and the statement cannot be true of both.

  python scripts/export_model_artifacts.py
  python scripts/export_model_artifacts.py --datasets fiveg_nidd --seeds 0

Regenerated by `make cards`.
"""
from __future__ import annotations

import argparse
import hashlib
import json
import logging
from pathlib import Path

import numpy as np

import joblib
import sklearn

from avert.benchmark.scaffold import make_scaffolded_detector
from avert.config import load_config
from avert.data.datasets import load_dataset
from avert.data.grouping import grouped_split, grouping_for
from avert.detectors.real import XGBoostDetector

REPO = Path(__file__).resolve().parents[1]
OUT = REPO / "artifacts" / "models"
DATASETS = ["fiveg_nidd", "ciciot2023", "ciciomt2024"]
SEEDS = [0, 1, 2, 3, 4]
N_CLASSES = 3
log = logging.getLogger("model_artifacts")


def sha256(p: Path) -> str:
    h = hashlib.sha256()
    with open(p, "rb") as fh:
        for chunk in iter(lambda: fh.read(1 << 20), b""):
            h.update(chunk)
    return h.hexdigest()


def export(dataset: str, seeds: list[int], n_train: int) -> list[dict]:
    data = load_dataset(dataset, load_config(f"datasets/{dataset}"))
    X, y = data.X, data.y
    entries = []

    for seed in seeds:
        rng = np.random.default_rng(seed)
        # Same fallback `XIntBench._prepare` uses. Passing data.grouping straight through
        # fails on a corpus with no recoverable session structure, and that corpus is in the
        # paper.
        grouping = data.grouping or grouping_for(data.name, len(X), None)
        split = grouped_split(grouping, seed=seed)
        tr = (np.sort(rng.choice(split.train, n_train, replace=False))
              if len(split.train) > n_train else split.train)
        te = split.test

        det = XGBoostDetector(n_estimators=150).fit(X[tr], y[tr])
        acc = float((det.predict(X[te]) == y[te]).mean())

        path = OUT / f"detector_{dataset}_seed{seed}.json"
        path.parent.mkdir(parents=True, exist_ok=True)
        det.booster.save_model(str(path))

        common = {
            "dataset": dataset, "seed": seed,
            "split_protocol": grouping.kind,
            "split_is_session_aware": bool(grouping.usable),
            "serves_cells": [f"{dataset}/class{i}/seed{seed}" for i in range(N_CLASSES)],
            "n_train_rows": int(len(tr)), "n_test_rows": int(len(te)),
            "feature_order": list(data.feature_names),
            "class_order": [str(c) for c in (data.label_names or [])],
        }
        entries.append({**common, "artifact": path.name, "kind": "detector",
                        "held_out_accuracy": round(acc, 4), "sha256": sha256(path)})

        # The A3 scaffold. Reproducing that attack needs the poisoned artifact itself, and the
        # poisoned part is the SURROGATE -- `ScaffoldedDetector.booster` deliberately returns the
        # real model, because an exact attributor reads through the wrapper untouched, which is
        # the whole finding. Saving `.booster` would therefore have shipped the clean model under
        # the scaffold's name. Export the surrogate, and record the routing parameters that make
        # the wrapper reconstructable.
        scaffold, real = make_scaffolded_detector(X[tr], y[tr], n_corrupt=12, seed=seed)
        params = {"n_corrupt": 12, "contamination": 0.3, "seed": seed, "n_estimators": 150}

        spath = OUT / f"scaffold_surrogate_{dataset}_seed{seed}.json"
        scaffold.surrogate.booster.save_model(str(spath))
        entries.append({**common, "artifact": spath.name, "kind": "scaffold_a3_surrogate",
                        "note": "The surrogate a Slack-style scaffold routes off-manifold probes "
                                "to, trained with the real model's 12 most important features "
                                "permuted. Rebuild the wrapper as ScaffoldedDetector(real, "
                                "surrogate, OODDetector(contamination=0.3, seed=seed)). An exact "
                                "attributor reads the real model and is NOT fooled -- that is "
                                "architectural, not an empirical finding.",
                        "scaffold_params": params, "sha256": sha256(spath)})

        # The wrapper's real component. Refitted from the same rows as the detector above, so
        # it should be the same model; exported with its own digest so that is checkable rather
        # than asserted, and the manifest records whether the two matched on this run.
        rpath = OUT / f"scaffold_real_{dataset}_seed{seed}.json"
        real.booster.save_model(str(rpath))
        entries.append({**common, "artifact": rpath.name, "kind": "scaffold_a3_real",
                        "note": "The component the scaffold routes non-probe inputs to.",
                        "scaffold_params": params, "sha256": sha256(rpath),
                        "identical_to_detector": sha256(rpath) == entries[-2]["sha256"]})

        # The router. A scikit-learn estimator, so joblib rather than JSON; the parameters
        # beside it rebuild it from the training rows without unpickling anything.
        opath = OUT / f"scaffold_ood_{dataset}_seed{seed}.joblib"
        joblib.dump(scaffold.ood, opath)
        entries.append({**common, "artifact": opath.name, "kind": "scaffold_a3_isolation_forest",
                        "note": "The isolation forest that decides which inputs are explainer "
                                "probes. Needs joblib and the scikit-learn version recorded "
                                "here; OODDetector(contamination=0.3, seed=seed).fit(X[tr]) "
                                "rebuilds it from the training rows instead.",
                        "scaffold_params": params, "sklearn_version": sklearn.__version__,
                        "sha256": sha256(opath)})
        log.info("%s seed %d: detector held-out accuracy %.4f (%s split), scaffold exported "
                 "(real identical to detector: %s)",
                 dataset, seed, acc, grouping.kind, entries[-2]["identical_to_detector"])
    return entries


def main() -> int:
    ap = argparse.ArgumentParser()
    ap.add_argument("--datasets", nargs="+", default=DATASETS)
    ap.add_argument("--seeds", nargs="+", type=int, default=SEEDS)
    ap.add_argument("--n-train", type=int, default=60_000)
    a = ap.parse_args()
    logging.basicConfig(level=logging.INFO, format="%(message)s")

    entries = []
    for ds in a.datasets:
        entries += export(ds, a.seeds, a.n_train)

    manifest = OUT / "manifest.json"
    manifest.write_text(json.dumps(
        {"generated_by": "scripts/export_model_artifacts.py",
         "note": "Regenerable from scripts/export_model_artifacts.py given the corpora. Every "
                 "entry below carries the sha256 of the file it names on the recorded "
                 "platform, so a reader can check what they got against what was produced; a "
                 "different XGBoost or numpy build can serialise the same model to different "
                 "bytes, so compare held-out accuracy too. One detector per (dataset, seed) "
                 "serves all three target classes of that cell, so 15 detectors cover the 45 "
                 "cells of the matrix.",
         "sklearn_version": sklearn.__version__,
         "artifacts": entries}, indent=1))
    log.info("exported %d artifacts to %s", len(entries), OUT)
    log.info("manifest: %s", manifest)
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
